# Generated by Django 6.0.6 on 2026-06-16 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='content',
            field=models.TextField(default='0'),
            preserve_default=False,
        ),
    ]
